# Generated by Django 5.0.2 on 2025-05-18 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistema_escolar_api', '0006_rename_horario_eventos_hora_final_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventos',
            name='cupo_maximo',
            field=models.IntegerField(blank=True, max_length=255, null=True),
        ),
    ]
