# Generated by Django 5.0.2 on 2025-05-18 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistema_escolar_api', '0007_alter_eventos_cupo_maximo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventos',
            name='hora_final',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='eventos',
            name='hora_inicio',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
