# Generated by Django 5.0.2 on 2025-05-19 01:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistema_escolar_api', '0008_alter_eventos_hora_final_alter_eventos_hora_inicio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventos',
            name='cupo_maximo',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
